name: CI

on:
  push:
    branches: ['main']
    tags: ['v*']

env:
  KO_DOCKER_REPO: ghcr.io/wilsonehusin

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - uses: actions/checkout@v2

      - uses: bindl-dev/bindl@main
        with:
          install-dir: bin

      - name: Authenticate ko
        shell: bash
        run: |
          set -ex
          make bin/ko
          echo "${{ github.token }}" | bin/ko login ghcr.io --username "${{ github.actor }}" --password-stdin

      - run: make ko/publish
        if: ${{ github.ref_type != 'tag' }}

      - run: make ko/release TAG=${{ github.ref_name }}
        if: ${{ github.ref_type == 'tag' }}
