name: Publish

on:
  push:
    branches: ['main']
    tags: ['v*']

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.19
      - uses: actions/checkout@v2

      - uses: imjasonh/setup-ko@v0.6
        env:
          # Required, otherwise the repo name will be included,
          # resulting in duplication.
          KO_DOCKER_REPO: ghcr.io/wilsonehusin

      - run: ko build --base-import-paths
        if: ${{ github.ref_type != 'tag' }}

      - run: ko build --base-import-paths --tags ${{ github.ref_name }}
        if: ${{ github.ref_type == 'tag' }}
